### ISSUE TITLE
plugin still references rollup-pluginutils 

### ISSUE THREAD

**Issue by danielart** [lopatnov/rollup-plugin-uglify#11]
**Describe the bug**
plugin still references rollup-pluginutils, which was moved and is now available at [@rollup/pluginutils](https://github.com/rollup/plugins)

**Additional context**
PR: #10 
(the old rollup-pluginutils have to be removed from package.json)

**Comment by lopatnov** [comment]
Hi @danielart, thanks. I'm going to update it in my next free time

**Comment by danielart** [comment]
Thanks, I opened a MR with the change just in case it helps you. Let me know if you want help with this 🚀

**Comment by lopatnov** [comment]
Please check, I've updated. It's good that you noticed it. Last time my projects are not connected with rollup.

**Comment by danielart** [comment]
Thanks Lopatnov, it works perfectly 👍
