### ISSUE TITLE
CI/CD Error: Cannot find module @rollup/pluginutils

### ISSUE THREAD

**Issue by paceaux** [lopatnov/rollup-plugin-uglify#13]
** **
Ci/CD pipeline shows
"cannot find module ' @rollup/pluginutils'
> Require stack:
- /node_modules/@lopatnov/rollup-plugin-uglify/dist/plugin.js
- rollup.config.js
- /node_modules/rollup/dist/shared/loadConfigFile.js
- /node_modules/rollup/dist/bin/rollup

** To reproduce: **
Rollup and `@lopatnov/rollup-plugin-uglify` are dependencies in a  Drupal project. 

We have the following rollup devdependencies:
```
    "@lopatnov/rollup-plugin-uglify": "^2.1.2",
    "rollup": "^2.61.1",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-globals": "^1.4.0",
    "rollup-plugin-node-resolve": "^5.2.0",
```

in our CI/CD pipeline, we execute the following npm script:

```
    "scripts:rollup": "rollup -c rollup.config.js",
```

And this is in our rollup config:
```
import commonjs from "rollup-plugin-commonjs";
import nodeResolve from "rollup-plugin-node-resolve";
import globals from "rollup-plugin-node-globals";
import builtins from "rollup-plugin-node-builtins";
import uglify from "@lopatnov/rollup-plugin-uglify";

export default [
  {
    input: "src/scripts/js/main.js",
    output: {
      file: "dist/js/main.min.js",
      format: "iife",
      name: "Main",
      sourcemap: true
    },
    plugins: [
      nodeResolve({ preferBuiltins: false }), // or `true`
      commonjs(),
      globals(),
      builtins(),
      uglify(),
    ],
  },
];

```

**Expected behavior**
We expect Rollup to build without issue

**Screenshots**

**Additional context**
We're running this in Gitlab.

**Comment by danielart** [comment]
Hi @paceaux , now rollup-plugin-uglify uses @rollup/pluginutils. I thing you'll have to install it as dev dependency on your project or use the previous version of this plugin. The change was done on #10

**Comment by lopatnov** [comment]
Dear @paceaux, did you try to install rollup-pluginutils: `npm i --save-dev @rollup/pluginutils`?

**Comment by paceaux** [comment]
@lopatnov we were running node >=14.19.1 both locally and in our CD environments. Clearing node_modules and removing package-lock.json did not work. 

@danielart Our temporary fix was to rollback and use 2.1.2 (our last known safe version). 

This change broke all of our CI builds. 

If this plugin now has a dependency on `@rollup/pluginutils` that we have to install, it might be good to update the readme (but also, why can't it be made a dependency of the plugin?)

I'm sure my employer won't be the only once experiencing broken builds.

**Comment by paceaux** [comment]
@lopatnov I think this issue could be resolved if `@rollup/pluginutils` were a `dependency` instead of a `devDependency`.

**Comment by danielart** [comment]
Indeed, it can be mark as a dependency, that will force to install the new pluginutils. But have in mind that the  previous versions had the old pluginutils version as a dependency, so you'll have to remove manually the old one or check how to manage both versions if you need the old one for other plugins. In any case, is a good idea to add it to readme/changelog and check which devdeps should be dependencies. @paceaux  thanks for the issue, feel free to open a PR with the changes. And if your team/company is using the plugin and is useful for you, a star or donation for this OpenSource plugin will be appreciated.

**Comment by paceaux** [comment]
@danielart  PR submitted. 

I'll talk to my company and see what we can do to support you. Do you have a "sponsor" page or links I can share?

**Comment by danielart** [comment]
I'm only a contributor, all merits to @lopatnov . But I think you can support him through this [Link](https://github.com/lopatnov/rollup-plugin-uglify#donate)

**Comment by lopatnov** [comment]
Dear @paceaux , I have a job. I think that a small amount of help will be more significant for [Izmail Perinatal Center ](https://dobro.ua/en/project/u_pologovii_budinok_neobkhidne_nove_obladnannia/). It could be small help for small people.

I've merged fix. Can you check? Is it working?

**Comment by lopatnov** [comment]
Inactive issue closed. Fixed!
